import assert from 'node:assert/strict';
import { fallbackColor, makeSample, previewKind, previewProjectPoint, unpackStates } from '../app.js';
import { BLOCKSTATE_IDS } from '../blocks-26.2.js';
import { BLOCK_COLORS_26_2 } from '../block-colors-26.2.js';

const base = previewProjectPoint({ x: 1, y: 2, z: 3 }, 10, 0, 0.68);
const rotated = previewProjectPoint({ x: 1, y: 2, z: 3 }, 10, Math.PI / 2, 0.68);
assert.deepEqual(Object.keys(base).sort(), ['depth', 'x', 'y']);
assert.ok(Number.isFinite(base.x) && Number.isFinite(base.y) && Number.isFinite(base.depth));
assert.notEqual(base.x, rotated.x, 'yaw must change horizontal projection');
assert.notEqual(base.depth, rotated.depth, 'yaw must change depth ordering');
assert.equal(previewKind('minecraft:stone_slab'), 'slab');
assert.equal(previewKind('minecraft:oak_stairs'), 'stairs');
assert.equal(previewKind('minecraft:redstone_wire'), 'redstone');
assert.equal(previewKind('minecraft:rail'), 'rail');
assert.equal(previewKind('minecraft:oak_trapdoor'), 'trapdoor');
assert.equal(Object.keys(BLOCK_COLORS_26_2).length, 1195);
assert.deepEqual(BLOCKSTATE_IDS.filter(id => !/(^|:)(air|cave_air|void_air)$/.test(id) && !BLOCK_COLORS_26_2[id]), []);
assert.equal(fallbackColor('minecraft:stone'), '#7e7e7e');
assert.equal(fallbackColor('minecraft:granite'), '#956756');
assert.equal(fallbackColor('minecraft:oak_planks'), '#a2834f');
assert.equal(fallbackColor('minecraft:warped_planks'), '#2b6963');
assert.equal(fallbackColor('minecraft:prismarine_bricks'), '#63ac9e');
assert.equal(fallbackColor('minecraft:prismarine_brick_slab'), '#63ac9e');
assert.equal(fallbackColor('minecraft:grass_block'), '#91bd59');
assert.equal(fallbackColor('minecraft:water'), '#3f76e4');
assert.equal(fallbackColor('minecraft:redstone_wire'), '#c62820');
assert.equal(fallbackColor('minecraft:spruce_leaves'), '#619961');
assert.equal(fallbackColor('minecraft:birch_leaves'), '#80a755');
assert.equal(fallbackColor('minecraft:attached_melon_stem'), '#e0c71c');
assert.equal(fallbackColor('minecraft:sea_lantern'), '#acc8be');
assert.notEqual(fallbackColor('minecraft:prismarine_bricks'), fallbackColor('minecraft:stone_bricks'));
const sampleRegion = makeSample().value.Regions.value['示例区域'];
const sampleDecoded = unpackStates(sampleRegion);
const sampleKinds = new Set([...sampleDecoded.values].map(index => previewKind(sampleDecoded.palette[index].Name.value)));
assert.ok(sampleKinds.has('redstone') && sampleKinds.has('stairs') && sampleKinds.has('plant') && sampleKinds.has('bed'));
console.log('PREVIEW_PROJECTION PASS yaw=pitch-aware shapes=5 colors=1195');
